"""add betting tables

Revision ID: 53eefc7f20cc
Revises: 004_add_performance_indexes
Create Date: 2025-12-11 20:49:53.341437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53eefc7f20cc'
down_revision: Union[str, None] = '004_add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_mobile_devices_user'), table_name='mobile_devices')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications')
    op.drop_index(op.f('idx_predictions_sport_timestamp'), table_name='predictions')
    op.drop_index(op.f('idx_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('idx_predictions_user_sport'), table_name='predictions')
    op.drop_index(op.f('idx_predictions_user_timestamp'), table_name='predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_predictions_user_timestamp'), 'predictions', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_predictions_user_sport'), 'predictions', ['user_id', 'sport'], unique=False)
    op.create_index(op.f('idx_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_index(op.f('idx_predictions_sport_timestamp'), 'predictions', ['sport', 'timestamp'], unique=False)
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id', 'delivered'], unique=False)
    op.create_index(op.f('idx_mobile_devices_user'), 'mobile_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###
