#!/usr/bin/env python3
"""
Generate Daily Parlays Script
==============================
Manually trigger generation of the three daily parlays (2-leg, 3-leg, 6-leg).
This is useful for testing or ensuring parlays are placed.
"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import asyncio
from src.services.parlay_builder import parlay_builder
from src.services.parlay_tracker import parlay_tracker
from src.services.bet_tracker import bet_tracker


async def generate_daily_parlays(user_id: str = "demo_user"):
    """Generate the three daily parlays."""
    
    # Get predictions from the autonomous betting engine
    print("📊 Fetching predictions from database...")
    print()
    
    # Use the autonomous engine's prediction fetching method
    predictions = await autonomous_engine._get_predictions(user_id)
    
    if not predictions or len(predictions) < 6:
        print(f"❌ Insufficient predictions found: {len(predictions) if predictions else 0}")
        print("   Need at least 6 predictions with betting metadata to build parlays")
        print("   Predictions should be generated by the head agent system")
        return
    
    print(f"✅ Found {len(predictions)} predictions with betting metadata")
    print()
    
    # Convert to format expected by parlay builder (already in correct format)
    betting_predictions = predictions
    
    # Get bankroll
    bankroll = await bet_tracker.get_bankroll(user_id)
    if not bankroll:
        print(f"❌ No bankroll found for user {user_id}")
        print("   Please initialize a bankroll using scripts/init_paper_trading.py")
        return
    
    print("=" * 80)
    print("🎯 GENERATING DAILY PARLAYS")
    print("=" * 80)
    print(f"Available predictions: {len(betting_predictions)}")
    print(f"Bankroll: ${bankroll.get('available_balance', 0):.2f}")
    print()
    
    parlay_amounts = {
        2: 25.0,   # $25 for 2-leg
        3: 25.0,   # $25 for 3-leg
        6: 50.0    # $50 for 6-leg
    }
    
    results = []
    
    # Build and place each parlay type
    for num_legs in [2, 3, 6]:
        print(f"\n{'='*80}")
        print(f"📊 Building {num_legs}-Leg Parlay")
        print(f"{'='*80}")
        
        # Determine risk level
        if num_legs == 2:
            risk_level = "conservative"
        elif num_legs == 3:
            risk_level = "moderate"
        else:
            risk_level = "aggressive"
        
        # Build parlay
        parlay = parlay_builder.build_parlay(betting_predictions, risk_level, num_legs=num_legs)
        
        if not parlay:
            print(f"❌ Failed to build {num_legs}-leg parlay")
            results.append({"legs": num_legs, "status": "failed", "reason": "Insufficient predictions"})
            continue
        
        print(f"✅ Built {num_legs}-leg parlay:")
        print(f"   Combined Odds: {parlay['combined_odds']}")
        print(f"   Combined Probability: {parlay['combined_probability']:.2%}")
        print(f"   Expected Value: {parlay['expected_value']:.2%}")
        print(f"   Legs:")
        for i, leg in enumerate(parlay['legs'], 1):
            print(f"      {i}. {leg.get('sport', 'unknown').upper()} | {leg.get('team', 'TBD')} @ {leg.get('odds', 0)}")
        
        # Prepare parlay data
        bet_amount = parlay_amounts.get(num_legs, 25.0)
        
        # Prepare leg data with game info
        legs = []
        earliest_game_date = None
        
        for leg_prediction in parlay['legs']:
            # Use the leg prediction directly (already has all needed info)
            leg_pred = leg_prediction
            
            # Track earliest game date
            leg_game_date = leg_pred.get("game_date")
            if leg_game_date:
                try:
                    from dateutil import parser
                    leg_date = parser.parse(leg_game_date) if isinstance(leg_game_date, str) else leg_game_date
                    if not earliest_game_date or leg_date < earliest_game_date:
                        earliest_game_date = leg_date
                except Exception:
                    pass
            
            legs.append({
                "sport": leg_pred.get("sport", "unknown"),
                "game_id": leg_pred.get("game_id", ""),
                "home_team": leg_pred.get("home_team"),
                "away_team": leg_pred.get("away_team"),
                "bet_type": leg_prediction.get("bet_type", "moneyline"),
                "team": leg_prediction.get("team"),
                "line": leg_prediction.get("line"),
                "odds": leg_prediction.get("odds", -110),
                "probability": leg_prediction.get("probability"),
                "edge": leg_prediction.get("edge")
            })
        
        # Store parlay
        parlay_data = {
            "legs": legs,
            "amount": bet_amount,
            "combined_odds": parlay['combined_odds'],
            "combined_probability": parlay['combined_probability'],
            "expected_edge": parlay.get('expected_value'),
            "combined_confidence": parlay.get('combined_probability'),  # Approximate
            "sportsbook": "paper_trading",
            "game_date": earliest_game_date
        }
        
        try:
            parlay_bet_id = await parlay_tracker.place_parlay(
                user_id, parlay_data, is_autonomous=False
            )
            print(f"✅ {num_legs}-leg parlay stored! Bet ID: {parlay_bet_id}")
            results.append({"legs": num_legs, "status": "success", "bet_id": parlay_bet_id})
        except Exception as e:
            print(f"❌ Error storing {num_legs}-leg parlay: {e}")
            results.append({"legs": num_legs, "status": "error", "error": str(e)})
    
    # Summary
    print()
    print("=" * 80)
    print("📊 SUMMARY")
    print("=" * 80)
    for result in results:
        status_emoji = "✅" if result['status'] == 'success' else "❌"
        print(f"{status_emoji} {result['legs']}-leg parlay: {result['status']}")
        if result.get('bet_id'):
            print(f"   Bet ID: {result['bet_id']}")


async def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate daily parlays")
    parser.add_argument("--user-id", type=str, default="demo_user", help="User ID")
    
    args = parser.parse_args()
    
    try:
        await generate_daily_parlays(user_id=args.user_id)
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    asyncio.run(main())

